version: "3.3"
services:
  server:
    build: server
    ports:
      - "8080:8080"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      #- "443:443"
